const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const path=require('path');
const assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const output=path.resolve(__dirname,'../screenshots');fs.mkdirSync(output,{recursive:true});
 await page.goto('http://127.0.0.1:5000');
 await page.waitForSelector('#countries path');await page.waitForSelector('tbody tr');
 await page.screenshot({path:path.join(output,'overview-1440.png'),fullPage:true});
 await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:path.join(output,'overview-1920.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#region').selectOption('eu-central-1');assert.match(await page.locator('#region-panel').innerText(),/FRANKFURT/);
 await page.locator('#zoom-in').click();assert.match(await page.locator('#map-transform').getAttribute('style'),/scale\(1.6\)/);
 await page.locator('#zoom-reset').click();assert.match(await page.locator('#map-transform').getAttribute('style'),/scale\(1\)/);
 await page.locator('#close-region').click();assert.equal(await page.locator('#region-panel').isVisible(),false);await page.locator('#open-region').click();
 await page.locator('#region').selectOption('ap-northeast-2');
 const original=await page.locator('tbody tr').count();await page.locator('[data-hours="1"]').click();assert((await page.locator('tbody tr').count())<original);await page.locator('[data-hours="24"]').click();
 await page.locator('#severity').selectOption('Critical');assert((await page.locator('tbody tr').count())>0);for(const text of await page.locator('tbody tr td:first-child').allTextContents())assert.equal(text,'Critical');
 await page.locator('#clear-filters').click();await page.locator('#source').selectOption('Trivy');for(const text of await page.locator('tbody tr td:nth-child(3)').allTextContents())assert.equal(text,'Trivy');
 await page.locator('#search').fill('no-result-xyz');assert.match(await page.locator('#content').innerText(),/데이터 없음/);await page.locator('#clear-filters').click();
 await page.locator('#search').fill('EVT-0003');await page.locator('tbody [data-event]').click();
 await page.locator('[data-action="approve"]').click();await page.locator('[data-action="cancel-approval"]').click();assert.match(await page.locator('#dialog-content').innerText(),/승인 대기/);
 await page.locator('[data-action="approve"]').click();await page.locator('[data-action="execute"]').click();await page.waitForSelector('[data-action="verify"]');assert.match(await page.locator('#dialog-content').innerText(),/재검증 대기/);
 await page.locator('[data-action="verify"]').click();await page.waitForFunction(()=>document.querySelector('.execution-flow').textContent.includes('통과'));assert.match(await page.locator('#dialog-content').innerText(),/해결/);
 const modalBox=await page.locator('#event-dialog').boundingBox();assert(Math.abs(modalBox.x+modalBox.width/2-960)<2,'Modal horizontally centered');
 await page.screenshot({path:path.join(output,'response-verified.png'),fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.locator('#event-dialog').isVisible(),false);
 await page.locator('#search').fill('EVT-0004');await page.locator('tbody [data-event]').click();await page.locator('[data-action="approve"]').click();await page.locator('[data-action="execute"]').click();await page.waitForSelector('[data-action="verify"]');await page.locator('[data-action="verify"]').click();await page.waitForFunction(()=>document.querySelector('.execution-flow').textContent.includes('실패'));assert.match(await page.locator('#dialog-content').innerText(),/재검증 실패/);await page.keyboard.press('Escape');
 await page.locator('#clear-filters').click();
 for(const view of ['events','vulnerabilities','infrastructure','responses','overview']){await page.locator(`nav [data-view="${view}"]`).click();assert.equal(await page.locator(`nav [data-view="${view}"]`).getAttribute('aria-current'),'page');}
 await page.locator('#status').selectOption('해결');const csvRows=await page.locator('tbody tr').count();const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;const csv=fs.readFileSync(await download.path(),'utf8');assert.equal(csv.trim().split('\r\n').length,csvRows+1);
 await page.locator('#clear-filters').click();await page.locator('#region').selectOption('global');assert.match(await page.locator('#region-panel').innerText(),/GLOBAL/);assert.equal(await page.locator('#markers [data-region="global"]').count(),0);
 await page.locator('#region').selectOption('ap-northeast-2');await page.locator('#environment').selectOption('staging');assert((await page.locator('tbody tr').count())>0);await page.locator('#environment').selectOption('production');
 await page.locator('#time-range').fill('144');await page.locator('#clear-filters').click();
 await page.locator('#zoom-reset').click();await page.waitForFunction(()=>document.querySelector('#toast').hidden);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'overview-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile page overflow');
 await page.setViewportSize({width:1440,height:900});
 // A real network failure must expose retry and recover after the source is available.
 await page.route('**/countries.geojson',route=>route.abort());await page.reload();await page.waitForSelector('#retry');assert.match(await page.locator('#load-state').innerText(),/불러오|fetch/i);await page.unroute('**/countries.geojson');await page.locator('#retry').click();await page.waitForSelector('#countries path');
 await page.waitForFunction(()=>document.querySelector('#load-state').hidden);await page.locator('#environment').selectOption('production');await page.locator('nav [data-view="infrastructure"]').click();await page.screenshot({path:path.join(output,'infrastructure-1440.png'),fullPage:true});
 await page.locator('nav [data-view="overview"]').click();
 await page.locator('#region').selectOption('ap-northeast-2');
 const count=await page.locator('tbody tr').count();assert.equal(Number(await page.locator('.region-total strong').innerText()),count);
 assert.equal((await page.locator('.donut-legend b').allTextContents()).reduce((sum,v)=>sum+Number(v),0),count);
 await page.emulateMedia({reducedMotion:'no-preference'});assert.equal(await page.locator('.pulse').first().evaluate(el=>getComputedStyle(el).animationName),'pulse');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.pulse').first().evaluate(el=>getComputedStyle(el).animationName),'none');
 await page.locator('#markers [data-region="eu-central-1"]').focus();await page.keyboard.press('Enter');assert.match(await page.locator('#region-panel').innerText(),/FRANKFURT/);assert.equal(await page.evaluate(()=>document.activeElement.dataset.region),'eu-central-1');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify({passed:true,checks:['1440 and 1920 layouts','390px no overflow','region and map controls','panel close/reopen','time/source/severity/search filters','approval cancel','execute distinct from verify','verification pass','verification fail','menu navigation','CSV filtered row count','global excluded from map','environment selection','network error and retry'],browserErrors:errors},null,2));
 console.log('PASS: all browser checks; screenshots saved to '+output);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

